//! TLS demo — one `Handler` served over HTTP *and* gRPC, with TLS wired
//! through the real `RuntimeBuilder` surface via `.http_tls()`/`.grpc_tls()`
//! and `PemTlsConfig`.
//!
//! Run plaintext (default, matches every other example in this crate):
//!     cargo run -p swe-edge-bootstrap --example tls-e2e
//!
//! Run with TLS, against a real self-signed certificate generated by the
//! `openssl` CLI (requires `openssl` on `PATH`):
//!     TLS_E2E_TLS=1 cargo run -p swe-edge-bootstrap --example tls-e2e
//!
//! `http_tls`/`grpc_tls` aren't feature-gated on `RuntimeBuilder` — there's
//! no Cargo feature to opt into here. What this example demonstrates is:
//!
//!   1. `.http_tls(PemTlsConfig::tls(cert, key))` — the HTTP listener stops
//!      accepting plaintext connections and only completes a real TLS
//!      handshake using the supplied cert/key (one-way TLS: the server
//!      authenticates, clients are not required to present a certificate).
//!   2. `.grpc_tls(...)` — the same `PemTlsConfig` wires TLS onto the gRPC
//!      listener through an identical seam (`edge-security-runtime-tls`'s
//!      acceptor, shared by both protocols).
//!   3. A plaintext client talking to either listener once TLS is
//!      configured gets rejected rather than silently served — this is
//!      exercised as an automated e2e test in
//!      `tests/tls_e2e_int_test.rs`, not just asserted here.
//!
//! Verify manually once running with `TLS_E2E_TLS=1`:
//!     curl -sk https://127.0.0.1:18590/echo -X POST -H 'content-type: application/json' -d '{"text":"hi"}'
//!     curl -s  http://127.0.0.1:18590/echo -X POST -H 'content-type: application/json' -d '{"text":"hi"}'   # rejected
//!
//! Split by responsibility rather than one `main()` doing everything:
//! [`handler`] owns the shared echo `Handler`, [`runtime_config`] owns bind
//! addresses, [`tls_setup`] owns whether/how TLS material gets generated —
//! `main` only wires the three together and serves.

mod handler;
mod runtime_config;
mod tls_setup;

use swe_edge_bootstrap::Runtime;

#[tokio::main]
async fn main() {
    let handler = handler::build_handler();
    let config = runtime_config::build_runtime_config();
    let tls = tls_setup::build_tls_material();

    let scheme = if tls.is_some() { "https" } else { "http" };
    println!("http: {scheme}://{}/echo", runtime_config::HTTP_BIND);
    println!(
        "grpc: {} ({})",
        runtime_config::GRPC_BIND,
        if tls.is_some() { "TLS" } else { "plaintext" }
    );
    if tls.is_none() {
        println!(
            "TLS disabled by default — set TLS_E2E_TLS=1 to serve with a real \
             self-signed certificate generated via the `openssl` CLI."
        );
    }

    let mut builder = Runtime::builder()
        .config(config)
        .http_route(handler.clone())
        .grpc_route(handler)
        .grpc_allow_unauthenticated();

    // Kept alive across `.serve()` below via `tls`'s own scope in `main` —
    // the temp cert/key files it owns must still exist when the TLS
    // acceptor reads them.
    if let Some(material) = tls.as_ref() {
        builder = builder
            .http_tls(material.config.clone())
            .grpc_tls(material.config.clone());
    }

    if let Err(e) = builder.serve().await {
        panic!("serve failed: {e}");
    }
}
