//! Integration test — proves TLS goes through `RuntimeBuilder` for real, per
//! the `http_tls`/`grpc_tls` (`PemTlsConfig`) feature epic: a real TLS
//! client handshake (against a genuine self-signed cert generated by the
//! `openssl` CLI, not a canned fixture) succeeds against an HTTP server
//! configured with `.http_tls(...)` and gets back the handler's actual
//! response, and a genuinely plaintext connection to that same TLS-required
//! server is rejected rather than silently served. The same pair is proven
//! for the gRPC listener via `.grpc_tls(...)`.
//!
//! Mirrors `grpc_e2e_int_test.rs`'s pattern: spawn `RuntimeBuilder::serve()`
//! on an ephemeral port via `free_port()`, sleep 200ms to let it bind, hit
//! it with a real client, assert on the real response, `handle.abort()`.
//!
//! `swe-edge-egress-grpc`'s client-side transport (`TonicGrpcEgress`) hardcodes
//! `hyper_rustls::HttpsConnectorBuilder::with_webpki_roots()` with no seam to
//! trust an arbitrary self-signed leaf cert (confirmed by inspecting its
//! source) — so unlike the HTTP side, there's no supported way to make it
//! complete a *full gRPC call* over TLS against our generated cert without
//! either patching that crate or duplicating a custom rustls-backed HTTP/2
//! client here. What *is* provable, and provable for real: (a) the gRPC
//! listener's TLS handshake itself succeeds against the exact certificate
//! `.grpc_tls(...)` was configured with — checked by shelling out to the
//! `openssl` CLI (already used for cert generation) as a real, independent
//! TLS client and asserting `Verify return code: 0 (ok)`; and (b) a
//! plaintext gRPC client is rejected outright, using the same
//! `TonicGrpcEgress` transport the plaintext-happy-path test elsewhere in
//! this crate already exercises, just now against a TLS-required server.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::{Arc, Once};
use std::time::Duration;

use async_trait::async_trait;
use edge_application::{Handler, HandlerError};
use edge_application_handler::{
    ExecutionRequest, IdRequest, IdResponse, PatternRequest, PatternResponse,
};
use swe_edge_bootstrap::{PemTlsConfig, Runtime, RuntimeConfig};
use swe_edge_egress_grpc::{GrpcChannelConfig, GrpcRequest, TransportConstruction};

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
struct TlsE2ePayload {
    text: String,
}
impl edge_application::Request for TlsE2ePayload {}
impl edge_application::Response for TlsE2ePayload {}

struct EchoHandler;

#[async_trait]
impl Handler for EchoHandler {
    type Request = TlsE2ePayload;
    type Response = TlsE2ePayload;

    fn id(&self, _req: IdRequest) -> Result<IdResponse, HandlerError> {
        Ok(IdResponse {
            id: "/echo".to_string(),
        })
    }

    fn pattern(&self, _req: PatternRequest) -> Result<PatternResponse, HandlerError> {
        Ok(PatternResponse {
            pattern: "/echo".to_string(),
        })
    }

    async fn execute(
        &self,
        req: ExecutionRequest<'_, TlsE2ePayload>,
    ) -> Result<TlsE2ePayload, HandlerError> {
        Ok(req.req)
    }
}

fn free_port() -> u16 {
    let listener = std::net::TcpListener::bind("127.0.0.1:0").expect("bind ephemeral port");
    listener.local_addr().expect("local_addr").port()
}

static CRYPTO_PROVIDER_INIT: Once = Once::new();

/// Installs a process-wide rustls `CryptoProvider` exactly once.
///
/// This test binary links both `swe-edge-egress-grpc` (whose `TonicGrpcEgress`
/// transport pulls in `hyper-rustls`'s `aws-lc-rs` backend) and
/// `edge-security-runtime-tls` (whose `DefaultAcceptorBuilder` builds a
/// server-side `rustls::ServerConfig` using the `ring` backend) — with both
/// backend features present in one binary, rustls refuses to auto-select
/// either and panics on first use unless a provider is installed explicitly.
/// `edge-security-runtime-tls`'s production `build_tls_acceptor` does not
/// install one itself (only its own unit tests do, as fixture setup), so
/// whichever side — client or server — happens to touch rustls first
/// depends on test scheduling. Every test here that spawns a
/// `.http_tls()`/`.grpc_tls()`-configured server calls this first so the
/// outcome doesn't depend on that race.
fn ensure_crypto_provider() {
    CRYPTO_PROVIDER_INIT.call_once(|| {
        rustls::crypto::ring::default_provider()
            .install_default()
            .expect("install a process-wide rustls CryptoProvider exactly once");
    });
}

/// Shell out to the real `openssl` CLI to generate a genuine self-signed
/// certificate and private key — no canned/checked-in fixture.
fn generate_self_signed_cert(dir: &Path) -> (PathBuf, PathBuf) {
    let cert_path = dir.join("cert.pem");
    let key_path = dir.join("key.pem");
    let status = Command::new("openssl")
        .arg("req")
        .arg("-x509")
        .arg("-newkey")
        .arg("rsa:2048")
        .arg("-nodes")
        .arg("-keyout")
        .arg(&key_path)
        .arg("-out")
        .arg(&cert_path)
        .arg("-days")
        .arg("1")
        .arg("-subj")
        .arg("/CN=localhost")
        .status()
        .expect("spawn `openssl` to generate a self-signed cert (openssl must be on PATH)");
    assert!(
        status.success(),
        "`openssl req` must succeed generating the self-signed cert"
    );
    (cert_path, key_path)
}

/// Run a real `openssl s_client` TLS handshake against `addr`, trusting
/// `ca_cert_path` (our own self-signed leaf, used as its own CA) for
/// verification. Returns the combined stdout+stderr for the caller to
/// assert against. Runs on a blocking thread since this shells out to a
/// real subprocess and blocks on its I/O.
async fn openssl_handshake(addr: String, ca_cert_path: PathBuf) -> String {
    tokio::time::timeout(
        Duration::from_secs(20),
        tokio::task::spawn_blocking(move || {
            let mut child = Command::new("openssl")
                .arg("s_client")
                .arg("-connect")
                .arg(&addr)
                .arg("-CAfile")
                .arg(&ca_cert_path)
                .stdin(Stdio::piped())
                .stdout(Stdio::piped())
                .stderr(Stdio::piped())
                .spawn()
                .expect("spawn `openssl s_client` (openssl must be on PATH)");

            // Write one newline then drop the handle to close stdin (EOF) —
            // `s_client` only exits once its stdin reaches EOF.
            {
                use std::io::Write;
                let mut stdin = child.stdin.take().expect("child stdin");
                let _ = stdin.write_all(b"\n");
            }

            let output = child
                .wait_with_output()
                .expect("wait for `openssl s_client` to exit");
            format!(
                "{}{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            )
        }),
    )
    .await
    .expect("openssl s_client must complete within 20s — a hang here means the TLS listener never responded")
    .expect("spawn_blocking task must not panic")
}

#[tokio::test]
async fn test_serve_http_route_tls_handshake_succeeds_and_echoes_payload_happy() {
    ensure_crypto_provider();
    let addr = format!("127.0.0.1:{}", free_port());

    let cert_dir = tempfile::tempdir().expect("create tempdir for generated TLS material");
    let (cert_path, key_path) = generate_self_signed_cert(cert_dir.path());

    let config = RuntimeConfig::default()
        .with_http_bind(addr.clone())
        .with_systemd_notify(false);

    let handle = tokio::spawn(async move {
        Runtime::builder()
            .config(config)
            .http_route(Arc::new(EchoHandler))
            .http_tls(PemTlsConfig::tls(
                cert_path.to_string_lossy().into_owned(),
                key_path.to_string_lossy().into_owned(),
            ))
            .grpc_allow_unauthenticated()
            .serve()
            .await
    });

    // Give the server a moment to bind before connecting.
    tokio::time::sleep(Duration::from_millis(200)).await;

    // A real TLS client accepting the self-signed cert (the demo's
    // one-way-TLS scenario has no platform-trusted CA behind it) — this is
    // the only relaxation from a production trust chain; the handshake
    // itself, the certificate served, and the application round trip are
    // all real.
    let client = reqwest::Client::builder()
        .danger_accept_invalid_certs(true)
        .timeout(Duration::from_secs(10))
        .build()
        .expect("build TLS-tolerant reqwest client");

    let payload = TlsE2ePayload {
        text: "hello-tls".to_string(),
    };
    let response = client
        .post(format!("https://{addr}/echo"))
        .json(&payload)
        .send()
        .await
        .expect("a real TLS handshake must succeed and the request must reach the handler");
    assert_eq!(
        response.status(),
        200,
        "the handler must accept the request over the TLS-terminated connection"
    );

    let echoed: TlsE2ePayload = response.json().await.expect("deserialize echoed payload");
    assert_eq!(
        echoed, payload,
        "the handler must echo back exactly what it received, proving the request \
         actually reached DefaultHttpJob -> Handler::execute through the TLS listener, \
         not just that a TCP handshake happened"
    );

    handle.abort();
}

#[tokio::test]
async fn test_serve_http_route_rejects_plaintext_connection_when_tls_required_negative() {
    ensure_crypto_provider();
    let addr = format!("127.0.0.1:{}", free_port());

    let cert_dir = tempfile::tempdir().expect("create tempdir for generated TLS material");
    let (cert_path, key_path) = generate_self_signed_cert(cert_dir.path());

    let config = RuntimeConfig::default()
        .with_http_bind(addr.clone())
        .with_systemd_notify(false);

    let handle = tokio::spawn(async move {
        Runtime::builder()
            .config(config)
            .http_route(Arc::new(EchoHandler))
            .http_tls(PemTlsConfig::tls(
                cert_path.to_string_lossy().into_owned(),
                key_path.to_string_lossy().into_owned(),
            ))
            .grpc_allow_unauthenticated()
            .serve()
            .await
    });

    tokio::time::sleep(Duration::from_millis(200)).await;

    // A genuinely plaintext client — no TLS anywhere in this request. If
    // `.http_tls()` wiring were broken (e.g. silently ignored, falling back
    // to the plaintext listener) this would succeed with a 200 and the
    // echoed payload, exactly like the happy-path test above. It must not.
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(5))
        .build()
        .expect("build plain reqwest client");

    let payload = TlsE2ePayload {
        text: "should-not-be-served".to_string(),
    };
    let result = client
        .post(format!("http://{addr}/echo"))
        .json(&payload)
        .send()
        .await;

    assert!(
        result.is_err(),
        "a plaintext request against a TLS-required listener must fail, got: {result:?}"
    );

    handle.abort();
}

#[tokio::test]
async fn test_serve_grpc_route_tls_handshake_succeeds_with_generated_cert_happy() {
    ensure_crypto_provider();
    let addr = format!("127.0.0.1:{}", free_port());

    let cert_dir = tempfile::tempdir().expect("create tempdir for generated TLS material");
    let (cert_path, key_path) = generate_self_signed_cert(cert_dir.path());
    let cert_path_for_client = cert_path.clone();

    let config = RuntimeConfig::default()
        .with_grpc_bind(addr.clone())
        .with_systemd_notify(false);

    let handle = tokio::spawn(async move {
        Runtime::builder()
            .config(config)
            .grpc_route(Arc::new(EchoHandler))
            .grpc_tls(PemTlsConfig::tls(
                cert_path.to_string_lossy().into_owned(),
                key_path.to_string_lossy().into_owned(),
            ))
            .grpc_allow_unauthenticated()
            .serve()
            .await
    });

    tokio::time::sleep(Duration::from_millis(200)).await;

    let output = openssl_handshake(addr, cert_path_for_client).await;
    assert!(
        output.contains("CONNECTED"),
        "openssl s_client must establish a TCP connection, got:\n{output}"
    );
    assert!(
        output.contains("Verify return code: 0 (ok)"),
        "a real TLS handshake against the gRPC listener must complete and verify \
         against the exact cert `.grpc_tls()` was configured with, got:\n{output}"
    );

    handle.abort();
}

#[tokio::test]
async fn test_serve_grpc_route_rejects_plaintext_connection_when_tls_required_negative() {
    ensure_crypto_provider();
    let addr = format!("127.0.0.1:{}", free_port());

    let cert_dir = tempfile::tempdir().expect("create tempdir for generated TLS material");
    let (cert_path, key_path) = generate_self_signed_cert(cert_dir.path());

    let config = RuntimeConfig::default()
        .with_grpc_bind(addr.clone())
        .with_systemd_notify(false);

    let handle = tokio::spawn(async move {
        Runtime::builder()
            .config(config)
            .grpc_route(Arc::new(EchoHandler))
            .grpc_tls(PemTlsConfig::tls(
                cert_path.to_string_lossy().into_owned(),
                key_path.to_string_lossy().into_owned(),
            ))
            .grpc_allow_unauthenticated()
            .serve()
            .await
    });

    tokio::time::sleep(Duration::from_millis(200)).await;

    // Genuinely plaintext gRPC client (`allow_plaintext()`, `http://`
    // endpoint) against a `.grpc_tls()`-required server. If the wiring were
    // broken (server silently still serving plaintext) this call would
    // succeed exactly like `grpc_e2e_int_test.rs`'s happy path does against
    // a real plaintext server. It must not.
    let client = TransportConstruction::create_transport_from_config(
        &GrpcChannelConfig::new(format!("http://{addr}")).allow_plaintext(),
    )
    .expect("create_transport_from_config must succeed building a plaintext client transport");

    let payload = TlsE2ePayload {
        text: "should-not-be-served".to_string(),
    };
    let body = serde_json::to_vec(&payload).expect("serialize payload");
    let request = GrpcRequest::new("echo", body, Duration::from_secs(5));

    let result = client.call_unary(request).await;
    assert!(
        result.is_err(),
        "a plaintext gRPC call against a TLS-required listener must fail, got: {result:?}"
    );

    handle.abort();
}
